-- CreateEnum
CREATE TYPE "Profession" AS ENUM ('ELECTRICIAN', 'PLUMBER', 'CARPENTER', 'PAINTER', 'CLEANER', 'HVAC_TECHNICIAN', 'LANDSCAPER', 'ROOFER', 'APPLIANCE_REPAIR_TECHNICIAN', 'PEST_CONTROL_SPECIALIST', 'MOVING_SERVICES_PROVIDER', 'INTERIOR_DESIGNER', 'HOME_SECURITY_SPECIALIST', 'SMART_HOME_INSTALLER');

-- CreateEnum
CREATE TYPE "ServiceType" AS ENUM ('ELECTRICAL', 'PLUMBING', 'CARPENTRY', 'PAINTING', 'CLEANING', 'HVAC', 'LANDSCAPING', 'ROOFING', 'APPLIANCE_REPAIR', 'PEST_CONTROL', 'MOVING_SERVICES', 'INTERIOR_DESIGN', 'HOME_SECURITY', 'SMART_HOME_INSTALLATION');

-- AlterTable
ALTER TABLE "technician_profiles" ADD COLUMN     "address" TEXT,
ADD COLUMN     "city" TEXT,
ADD COLUMN     "description" TEXT,
ADD COLUMN     "district" TEXT,
ADD COLUMN     "isApproved" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "profession" "Profession",
ADD COLUMN     "responseTime" INTEGER,
ADD COLUMN     "serviceArea" "ServiceType";

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "lastLoginAt" TIMESTAMP(3);
